runtime: python
env: flex
vm: true
entrypoint: gunicorn -b :$PORT main:app
threadsafe: true

runtime_config:
    python_version: 3

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
