runtime: python38
instance_class: F2

env_variables:
    CLOUD_STORAGE_BUCKET: coeai-tabular

handlers:
- url: /static
  static_dir: static
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
